# docker-compose.yml

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=SECRET
      - DATABASE_URL=postgresql://postgres:your_secure_password@collabydraw-db:5432/collabydraw
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    depends_on:
      - websocket
      - database

  websocket:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.websocket 
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=SECRET
      - DATABASE_URL=postgresql://postgres:your_secure_password@collabydraw-db:5432/collabydraw
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    container_name: collabydraw-db
    environment:
      POSTGRES_DB: collabydraw
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: